/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AboutResponse } from '../../models/about-response';

export interface GetAbout$Params {
}

export function getAbout(http: HttpClient, rootUrl: string, params?: GetAbout$Params, context?: HttpContext): Observable<StrictHttpResponse<AboutResponse>> {
  const rb = new RequestBuilder(rootUrl, getAbout.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AboutResponse>;
    })
  );
}

getAbout.PATH = '/api/v1/about';
