/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagResponse } from '../../models/tag-response';

export interface GetTags$Params {
  storageId: string;
}

export function getTags(http: HttpClient, rootUrl: string, params: GetTags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TagResponse>>> {
  const rb = new RequestBuilder(rootUrl, getTags.PATH, 'get');
  if (params) {
    rb.path('storageId', params.storageId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TagResponse>>;
    })
  );
}

getTags.PATH = '/api/v1/storages/{storageId}/tags';
