/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemRequest } from '../../models/item-request';

export interface UpdateItem$Params {
  storageId: string;
  itemId: string;

/**
 * Double-submit CSRF token. Obtain it from GET /auth/csrf (which sets the JS-readable XSRF-TOKEN cookie) and echo the value here.
 */
  'X-XSRF-TOKEN': string;
      body: ItemRequest
}

export function updateItem(http: HttpClient, rootUrl: string, params: UpdateItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateItem.PATH, 'put');
  if (params) {
    rb.path('storageId', params.storageId, {});
    rb.path('itemId', params.itemId, {});
    rb.header('X-XSRF-TOKEN', params['X-XSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateItem.PATH = '/api/v1/storages/{storageId}/items/{itemId}';
