/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpiryStatus } from './expiry-status';

/**
 * Each possible value of `ExpiryStatus`
 */
export const EXPIRY_STATUS: ExpiryStatus[] = [
  'Ok',
  'ExpiringSoon',
  'Expired'
];