/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationPreviewResponse {
  alreadyMember: boolean;
  ownerName: string;
  storageId: string;
  storageName: string;
}
