/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpiryStatus } from '../models/expiry-status';
import { Unit } from '../models/unit';
export interface ItemResponse {
  amount: number;
  expiryDate: (string | null);
  expiryStatus: ExpiryStatus;
  id: string;
  name: string;
  productionDate: (string | null);
  unit: Unit;
}
