/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Unit } from '../models/unit';
export interface ItemRequest {
  amount: number;
  expiryDate: (string | null);
  name: string;
  productionDate: (string | null);
  unit: Unit;
}
