/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemStatisticsResponse {
  byUnit: {
[key: string]: number;
};
  expired: number;
  expiringSoon: number;
  total: number;
  withExpiryDate: number;
  withProductionDate: number;
}
