/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StorageStatisticsResponse {
  empty: number;
  itemsPerStorageMax: number;
  itemsPerStorageMedian: number;
  shared: number;
  total: number;
}
