/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StorageMemberResponse {
  displayName: string;
  isOwner: boolean;
  joinedAt: (string | null);
  userId: string;
}
