/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StorageResponse {
  expiredCount: number;
  expiringSoonCount: number;
  id: string;
  itemCount: number;
  name: string;
}
