/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ThirdPartyComponentResponse {
  copyright: (string | null);
  license: string;
  name: string;
  text: (string | null);
  url: (string | null);
  version: string;
}
