/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Unit } from './unit';

/**
 * Each possible value of `Unit`
 */
export const UNIT: Unit[] = [
  'Piece',
  'Gram',
  'Kilogram',
  'Milliliter',
  'Liter',
  'Pack'
];