/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserStatisticsResponse {
  byIssuer: {
[key: string]: number;
};
  newLast30Days: number;
  newLast7Days: number;
  total: number;
  withoutAnyStorage: number;
}
