/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetStorages$Params as GetStorages$Params } from './fn/storages/get-storages';
export { getStorages as getStorages } from './fn/storages/get-storages';
export type { CreateStorage$Params as CreateStorage$Params } from './fn/storages/create-storage';
export { createStorage as createStorage } from './fn/storages/create-storage';
export type { RenameStorage$Params as RenameStorage$Params } from './fn/storages/rename-storage';
export { renameStorage as renameStorage } from './fn/storages/rename-storage';
export type { DeleteStorage$Params as DeleteStorage$Params } from './fn/storages/delete-storage';
export { deleteStorage as deleteStorage } from './fn/storages/delete-storage';
export type { GetItems$Params as GetItems$Params } from './fn/items/get-items';
export { getItems as getItems } from './fn/items/get-items';
export type { AddItem$Params as AddItem$Params } from './fn/items/add-item';
export { addItem as addItem } from './fn/items/add-item';
export type { UpdateItem$Params as UpdateItem$Params } from './fn/items/update-item';
export { updateItem as updateItem } from './fn/items/update-item';
export type { DeleteItem$Params as DeleteItem$Params } from './fn/items/delete-item';
export { deleteItem as deleteItem } from './fn/items/delete-item';
