/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AboutResponse } from '../models/about-response';
import { getAbout } from '../fn/about/get-about';
import { GetAbout$Params } from '../fn/about/get-about';

@Injectable({ providedIn: 'root' })
export class AboutService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAbout()` */
  static readonly GetAboutPath = '/api/v1/about';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAbout()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbout$Response(params?: GetAbout$Params, context?: HttpContext): Observable<StrictHttpResponse<AboutResponse>> {
    const obs = getAbout(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAbout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAbout(params?: GetAbout$Params, context?: HttpContext): Observable<AboutResponse> {
    const resp = this.getAbout$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AboutResponse>): AboutResponse => r.body)
    );
  }

}
