/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUsageStatistics } from '../fn/admin/get-usage-statistics';
import { GetUsageStatistics$Params } from '../fn/admin/get-usage-statistics';
import { UsageStatisticsResponse } from '../models/usage-statistics-response';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUsageStatistics()` */
  static readonly GetUsageStatisticsPath = '/api/v1/admin/statistics';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsageStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsageStatistics$Response(params?: GetUsageStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<UsageStatisticsResponse>> {
    const obs = getUsageStatistics(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsageStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsageStatistics(params?: GetUsageStatistics$Params, context?: HttpContext): Observable<UsageStatisticsResponse> {
    const resp = this.getUsageStatistics$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UsageStatisticsResponse>): UsageStatisticsResponse => r.body)
    );
  }

}
