/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addItem } from '../fn/items/add-item';
import { AddItem$Params } from '../fn/items/add-item';
import { deleteItem } from '../fn/items/delete-item';
import { DeleteItem$Params } from '../fn/items/delete-item';
import { getItems } from '../fn/items/get-items';
import { GetItems$Params } from '../fn/items/get-items';
import { ItemResponse } from '../models/item-response';
import { updateItem } from '../fn/items/update-item';
import { UpdateItem$Params } from '../fn/items/update-item';

@Injectable({ providedIn: 'root' })
export class ItemsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getItems()` */
  static readonly GetItemsPath = '/api/v1/storages/{storageId}/items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItems$Response(params: GetItems$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemResponse>>> {
    const obs = getItems(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItems(params: GetItems$Params, context?: HttpContext): Observable<Array<ItemResponse>> {
    const resp = this.getItems$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ItemResponse>>): Array<ItemResponse> => r.body)
    );
  }

  /** Path part for operation `addItem()` */
  static readonly AddItemPath = '/api/v1/storages/{storageId}/items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem$Response(params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    const obs = addItem(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem(params: AddItem$Params, context?: HttpContext): Observable<string> {
    const resp = this.addItem$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `updateItem()` */
  static readonly UpdateItemPath = '/api/v1/storages/{storageId}/items/{itemId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateItem$Response(params: UpdateItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateItem(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateItem(params: UpdateItem$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateItem$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteItem()` */
  static readonly DeleteItemPath = '/api/v1/storages/{storageId}/items/{itemId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItem$Response(params: DeleteItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteItem(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItem(params: DeleteItem$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteItem$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
