/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AcceptedInvitationResponse } from '../models/accepted-invitation-response';
import { acceptInvitation } from '../fn/sharing/accept-invitation';
import { AcceptInvitation$Params } from '../fn/sharing/accept-invitation';
import { CreatedInvitationResponse } from '../models/created-invitation-response';
import { createInvitation } from '../fn/sharing/create-invitation';
import { CreateInvitation$Params } from '../fn/sharing/create-invitation';
import { deactivateInvitation } from '../fn/sharing/deactivate-invitation';
import { DeactivateInvitation$Params } from '../fn/sharing/deactivate-invitation';
import { getInvitation } from '../fn/sharing/get-invitation';
import { GetInvitation$Params } from '../fn/sharing/get-invitation';
import { getMembers } from '../fn/sharing/get-members';
import { GetMembers$Params } from '../fn/sharing/get-members';
import { InvitationPreviewResponse } from '../models/invitation-preview-response';
import { InvitationStatusResponse } from '../models/invitation-status-response';
import { leaveStorage } from '../fn/sharing/leave-storage';
import { LeaveStorage$Params } from '../fn/sharing/leave-storage';
import { previewInvitation } from '../fn/sharing/preview-invitation';
import { PreviewInvitation$Params } from '../fn/sharing/preview-invitation';
import { removeMember } from '../fn/sharing/remove-member';
import { RemoveMember$Params } from '../fn/sharing/remove-member';
import { StorageMemberResponse } from '../models/storage-member-response';

@Injectable({ providedIn: 'root' })
export class SharingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getInvitation()` */
  static readonly GetInvitationPath = '/api/v1/storages/{storageId}/invitation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInvitation()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvitation$Response(params: GetInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationStatusResponse>> {
    const obs = getInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInvitation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvitation(params: GetInvitation$Params, context?: HttpContext): Observable<InvitationStatusResponse> {
    const resp = this.getInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InvitationStatusResponse>): InvitationStatusResponse => r.body)
    );
  }

  /** Path part for operation `createInvitation()` */
  static readonly CreateInvitationPath = '/api/v1/storages/{storageId}/invitation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInvitation()` instead.
   *
   * This method doesn't expect any request body.
   */
  createInvitation$Response(params: CreateInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatedInvitationResponse>> {
    const obs = createInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInvitation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createInvitation(params: CreateInvitation$Params, context?: HttpContext): Observable<CreatedInvitationResponse> {
    const resp = this.createInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CreatedInvitationResponse>): CreatedInvitationResponse => r.body)
    );
  }

  /** Path part for operation `deactivateInvitation()` */
  static readonly DeactivateInvitationPath = '/api/v1/storages/{storageId}/invitation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deactivateInvitation()` instead.
   *
   * This method doesn't expect any request body.
   */
  deactivateInvitation$Response(params: DeactivateInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deactivateInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deactivateInvitation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deactivateInvitation(params: DeactivateInvitation$Params, context?: HttpContext): Observable<void> {
    const resp = this.deactivateInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getMembers()` */
  static readonly GetMembersPath = '/api/v1/storages/{storageId}/members';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMembers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMembers$Response(params: GetMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorageMemberResponse>>> {
    const obs = getMembers(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMembers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMembers(params: GetMembers$Params, context?: HttpContext): Observable<Array<StorageMemberResponse>> {
    const resp = this.getMembers$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<StorageMemberResponse>>): Array<StorageMemberResponse> => r.body)
    );
  }

  /** Path part for operation `removeMember()` */
  static readonly RemoveMemberPath = '/api/v1/storages/{storageId}/members/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeMember()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMember$Response(params: RemoveMember$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = removeMember(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeMember$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMember(params: RemoveMember$Params, context?: HttpContext): Observable<void> {
    const resp = this.removeMember$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `leaveStorage()` */
  static readonly LeaveStoragePath = '/api/v1/storages/{storageId}/membership';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `leaveStorage()` instead.
   *
   * This method doesn't expect any request body.
   */
  leaveStorage$Response(params: LeaveStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = leaveStorage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `leaveStorage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  leaveStorage(params: LeaveStorage$Params, context?: HttpContext): Observable<void> {
    const resp = this.leaveStorage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `previewInvitation()` */
  static readonly PreviewInvitationPath = '/api/v1/invitations/preview';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `previewInvitation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  previewInvitation$Response(params: PreviewInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationPreviewResponse>> {
    const obs = previewInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `previewInvitation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  previewInvitation(params: PreviewInvitation$Params, context?: HttpContext): Observable<InvitationPreviewResponse> {
    const resp = this.previewInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<InvitationPreviewResponse>): InvitationPreviewResponse => r.body)
    );
  }

  /** Path part for operation `acceptInvitation()` */
  static readonly AcceptInvitationPath = '/api/v1/invitations/accept';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `acceptInvitation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptInvitation$Response(params: AcceptInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<AcceptedInvitationResponse>> {
    const obs = acceptInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `acceptInvitation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptInvitation(params: AcceptInvitation$Params, context?: HttpContext): Observable<AcceptedInvitationResponse> {
    const resp = this.acceptInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AcceptedInvitationResponse>): AcceptedInvitationResponse => r.body)
    );
  }

}
