/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createStorage } from '../fn/storages/create-storage';
import { CreateStorage$Params } from '../fn/storages/create-storage';
import { deleteStorage } from '../fn/storages/delete-storage';
import { DeleteStorage$Params } from '../fn/storages/delete-storage';
import { getStorages } from '../fn/storages/get-storages';
import { GetStorages$Params } from '../fn/storages/get-storages';
import { renameStorage } from '../fn/storages/rename-storage';
import { RenameStorage$Params } from '../fn/storages/rename-storage';
import { StorageResponse } from '../models/storage-response';

@Injectable({ providedIn: 'root' })
export class StoragesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getStorages()` */
  static readonly GetStoragesPath = '/api/v1/storages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStorages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStorages$Response(params?: GetStorages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorageResponse>>> {
    const obs = getStorages(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStorages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStorages(params?: GetStorages$Params, context?: HttpContext): Observable<Array<StorageResponse>> {
    const resp = this.getStorages$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<StorageResponse>>): Array<StorageResponse> => r.body)
    );
  }

  /** Path part for operation `createStorage()` */
  static readonly CreateStoragePath = '/api/v1/storages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createStorage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStorage$Response(params: CreateStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageResponse>> {
    const obs = createStorage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createStorage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStorage(params: CreateStorage$Params, context?: HttpContext): Observable<StorageResponse> {
    const resp = this.createStorage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StorageResponse>): StorageResponse => r.body)
    );
  }

  /** Path part for operation `renameStorage()` */
  static readonly RenameStoragePath = '/api/v1/storages/{storageId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `renameStorage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameStorage$Response(params: RenameStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageResponse>> {
    const obs = renameStorage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `renameStorage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameStorage(params: RenameStorage$Params, context?: HttpContext): Observable<StorageResponse> {
    const resp = this.renameStorage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StorageResponse>): StorageResponse => r.body)
    );
  }

  /** Path part for operation `deleteStorage()` */
  static readonly DeleteStoragePath = '/api/v1/storages/{storageId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStorage()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStorage$Response(params: DeleteStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteStorage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStorage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStorage(params: DeleteStorage$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteStorage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
