using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StoreIt.Domain;

namespace StoreIt.Infrastructure;

/// <summary>
/// Mapping via configuration classes — no persistence attributes on domain entities
/// (coding guidelines: frameworks are details at the edges).
/// </summary>
public sealed class StorageConfiguration : IEntityTypeConfiguration<Storage>
{
    public void Configure(EntityTypeBuilder<Storage> builder)
    {
        builder.ToTable("storages");
        builder.HasKey(s => s.Id);
        // IDs are generated by the domain (constructors) — without this, EF treats
        // entities with non-empty keys as existing and issues UPDATE instead of INSERT
        builder.Property(s => s.Id).ValueGeneratedNever();
        builder.Property(s => s.Name).IsRequired().HasMaxLength(200);

        builder.Property(s => s.OwnerId).IsRequired();
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(s => s.OwnerId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(s => s.OwnerId);

        // Aggregate: items live and die with their storage (EC-06: no orphans).
        // Required FK — removing an item from the collection deletes the row
        // instead of nulling the FK (AC-09).
        builder
            .HasMany(s => s.Items)
            .WithOne()
            .HasForeignKey("storage_id")
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        builder
            .Navigation(s => s.Items)
            .HasField("_items")
            .UsePropertyAccessMode(PropertyAccessMode.Field);

        // SPEC-007 / ADR-008: members are aggregate children like items — they live and die
        // with the storage (cascade) and are reachable only through it.
        builder
            .HasMany(s => s.Members)
            .WithOne()
            .HasForeignKey(m => m.StorageId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        builder
            .Navigation(s => s.Members)
            .HasField("_members")
            .UsePropertyAccessMode(PropertyAccessMode.Field);
    }
}

/// <summary>SPEC-007: membership rows; composite key, index for the access filter.</summary>
public sealed class StorageMemberConfiguration : IEntityTypeConfiguration<StorageMember>
{
    public void Configure(EntityTypeBuilder<StorageMember> builder)
    {
        builder.ToTable("storage_members");
        builder.HasKey(m => new { m.StorageId, m.UserId });
        builder.Property(m => m.JoinedAt).IsRequired();

        // Deleting a user account (SPEC-006) ends their memberships (SPEC-007 D5 / AC-21).
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(m => m.UserId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        // The global filter asks "is the current user a member of this storage?" per storage.
        builder.HasIndex(m => new { m.UserId, m.StorageId });
    }
}

/// <summary>SPEC-007 D2: one invitation per storage, token stored hashed.</summary>
public sealed class StorageInvitationConfiguration : IEntityTypeConfiguration<StorageInvitation>
{
    public void Configure(EntityTypeBuilder<StorageInvitation> builder)
    {
        builder.ToTable("storage_invitations");
        builder.HasKey(i => i.StorageId);
        builder.Property(i => i.TokenHash).IsRequired().HasMaxLength(64);
        builder.HasIndex(i => i.TokenHash).IsUnique();
        builder.Property(i => i.CreatedAt).IsRequired();
        builder.Property(i => i.ExpiresAt).IsRequired();

        builder
            .HasOne<Storage>()
            .WithOne()
            .HasForeignKey<StorageInvitation>(i => i.StorageId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);
    }
}

public sealed class ItemConfiguration : IEntityTypeConfiguration<Item>
{
    public void Configure(EntityTypeBuilder<Item> builder)
    {
        builder.ToTable("items");
        builder.HasKey(i => i.Id);
        builder.Property(i => i.Id).ValueGeneratedNever();
        builder.Property(i => i.Name).IsRequired().HasMaxLength(200);

        // SPEC-001: one decimal place; wide precision so any domain-valid amount
        // (> 0) persists without SaveChanges overflow — validation and storage agree.
        builder.Property(i => i.Amount).HasPrecision(18, 1);

        // Locale-neutral enum code as readable string (arc42 §8 i18n)
        builder.Property(i => i.Unit).HasConversion<string>().HasMaxLength(20);

        builder.Property(i => i.ExpiryDate);
        builder.Property(i => i.ProductionDate);
    }
}
