using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StoreIt.Domain;

namespace StoreIt.Infrastructure;

/// <summary>
/// Mapping via configuration classes — no persistence attributes on domain entities
/// (coding guidelines: frameworks are details at the edges).
/// </summary>
public sealed class StorageConfiguration : IEntityTypeConfiguration<Storage>
{
    public void Configure(EntityTypeBuilder<Storage> builder)
    {
        builder.ToTable("storages");
        builder.HasKey(s => s.Id);
        // IDs are generated by the domain (constructors) — without this, EF treats
        // entities with non-empty keys as existing and issues UPDATE instead of INSERT
        builder.Property(s => s.Id).ValueGeneratedNever();
        builder.Property(s => s.Name).IsRequired().HasMaxLength(200);

        builder.Property(s => s.OwnerId).IsRequired();
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(s => s.OwnerId)
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(s => s.OwnerId);

        // Aggregate: items live and die with their storage (EC-06: no orphans).
        // Required FK — removing an item from the collection deletes the row
        // instead of nulling the FK (AC-09).
        builder
            .HasMany(s => s.Items)
            .WithOne()
            .HasForeignKey("storage_id")
            .IsRequired()
            .OnDelete(DeleteBehavior.Cascade);

        builder
            .Navigation(s => s.Items)
            .HasField("_items")
            .UsePropertyAccessMode(PropertyAccessMode.Field);
    }
}

public sealed class ItemConfiguration : IEntityTypeConfiguration<Item>
{
    public void Configure(EntityTypeBuilder<Item> builder)
    {
        builder.ToTable("items");
        builder.HasKey(i => i.Id);
        builder.Property(i => i.Id).ValueGeneratedNever();
        builder.Property(i => i.Name).IsRequired().HasMaxLength(200);

        // SPEC-001: one decimal place; wide precision so any domain-valid amount
        // (> 0) persists without SaveChanges overflow — validation and storage agree.
        builder.Property(i => i.Amount).HasPrecision(18, 1);

        // Locale-neutral enum code as readable string (arc42 §8 i18n)
        builder.Property(i => i.Unit).HasConversion<string>().HasMaxLength(20);

        builder.Property(i => i.ExpiryDate);
        builder.Property(i => i.ProductionDate);
    }
}
