using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StoreIt.Domain;

namespace StoreIt.Infrastructure;

/// <summary>
/// Mapping for the User aggregate (SPEC-003).
/// No persistence attributes on the domain entity — frameworks are details at the edges.
/// </summary>
public sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("users");
        builder.HasKey(u => u.Id);
        // IDs are generated by the domain — without this, EF treats entities with
        // non-empty keys as existing and issues UPDATE instead of INSERT.
        builder.Property(u => u.Id).ValueGeneratedNever();
        builder.Property(u => u.Issuer).IsRequired().HasMaxLength(500);
        builder.Property(u => u.Subject).IsRequired().HasMaxLength(500);
        builder.Property(u => u.Email).HasMaxLength(320);
        builder.Property(u => u.DisplayName).IsRequired().HasMaxLength(200);
        builder.Property(u => u.CreatedAt).IsRequired();

        // SPEC-003 EC-01: the identity key (Issuer, Subject) must be globally unique.
        builder.HasIndex(u => new { u.Issuer, u.Subject }).IsUnique();
    }
}
