/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorageRequest } from '../../models/storage-request';
import { StorageResponse } from '../../models/storage-response';

export interface CreateStorage$Params {
      body: StorageRequest
}

export function createStorage(http: HttpClient, rootUrl: string, params: CreateStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageResponse>> {
  const rb = new RequestBuilder(rootUrl, createStorage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorageResponse>;
    })
  );
}

createStorage.PATH = '/api/v1/storages';
