/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorageResponse } from '../../models/storage-response';

export interface GetStorages$Params {
}

export function getStorages(http: HttpClient, rootUrl: string, params?: GetStorages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorageResponse>>> {
  const rb = new RequestBuilder(rootUrl, getStorages.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StorageResponse>>;
    })
  );
}

getStorages.PATH = '/api/v1/storages';
