/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorageResponse } from '../../models/storage-response';

export interface GetStorage$Params {
  storageId: string;
}

export function getStorage(http: HttpClient, rootUrl: string, params: GetStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageResponse>> {
  const rb = new RequestBuilder(rootUrl, getStorage.PATH, 'get');
  if (params) {
    rb.path('storageId', params.storageId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorageResponse>;
    })
  );
}

getStorage.PATH = '/api/v1/storages/{storageId}';
