/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatedInvitationResponse } from '../../models/created-invitation-response';

export interface CreateInvitation$Params {
  storageId: string;

/**
 * Double-submit CSRF token. Obtain it from GET /auth/csrf (which sets the JS-readable XSRF-TOKEN cookie) and echo the value here.
 */
  'X-XSRF-TOKEN': string;
}

export function createInvitation(http: HttpClient, rootUrl: string, params: CreateInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatedInvitationResponse>> {
  const rb = new RequestBuilder(rootUrl, createInvitation.PATH, 'post');
  if (params) {
    rb.path('storageId', params.storageId, {});
    rb.header('X-XSRF-TOKEN', params['X-XSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatedInvitationResponse>;
    })
  );
}

createInvitation.PATH = '/api/v1/storages/{storageId}/invitation';
