/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitationPreviewResponse } from '../../models/invitation-preview-response';
import { InvitationTokenRequest } from '../../models/invitation-token-request';

export interface PreviewInvitation$Params {

/**
 * Double-submit CSRF token. Obtain it from GET /auth/csrf (which sets the JS-readable XSRF-TOKEN cookie) and echo the value here.
 */
  'X-XSRF-TOKEN': string;
      body: InvitationTokenRequest
}

export function previewInvitation(http: HttpClient, rootUrl: string, params: PreviewInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationPreviewResponse>> {
  const rb = new RequestBuilder(rootUrl, previewInvitation.PATH, 'post');
  if (params) {
    rb.header('X-XSRF-TOKEN', params['X-XSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationPreviewResponse>;
    })
  );
}

previewInvitation.PATH = '/api/v1/invitations/preview';
